language: node_js
node_js:
 - 12.13.0
before_install:
  - npm i -g firebase-tools
  - npm install -g eslint
script:
  - npm run lint
after_success:
  - npm run deploy
notifications:
  email: false
deploy:
  provider: firebase
  token: $FIREBASE_TOKEN
branches:
  only:
    - master